---
theme: jekyll-theme-slate
title: Amy Palomino     Data Analyst
description: Portfolio of work
---

# Layout

show_social: true 

# Menu 

navigation:
  - {file: "index.md", titles: "Home", icon: home}
  - {file: "README.md", titles: "Projects", icon: address-card}
  - {file: "Amy_CV.pdf", titles: "CV", icon: address-card}

external:               # see http://fontawesome.com.icons
- {title: Mail, icon: envelope,url:"mailto.amy.pal@outlook.com"}
- {title: Github, icon: github,url:"https://github.com/amypal"}
- {title: Linkedin, icon: IN,url:"https://linkedin.com/in/amy-palomino-92894a221m"}
